blank_issues_enabled: true
contact_links:
  - name: ğŸ“ Dokumentation
    url: https://github.com/TimBoBN/schulbuddy/blob/main/README.md
    about: Sieh dir unsere Dokumentation an, bevor du ein Issue erstellst
  - name: ğŸ”’ SicherheitslÃ¼cke melden
    url: https://github.com/TimBoBN/schulbuddy/blob/main/SECURITY.md
    about: Bitte melde SicherheitslÃ¼cken gemÃ¤ÃŸ unserer Security Policy
